### ISSUE TITLE
Pass environment variables through to job

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/hpcpy#25]
[`payu`](https://github.com/payu-org/payu/) runs and then re-submits itself so that it can run a model a number of times sequentially. 

It passes state information, like the number of runs remaining, between invocations using environment variables. Is it possible to pass environment variables into the PBS submission using HPCpy?

**Comment by bschroeter** [comment]
@aidanheerdegen, this is currently possible using the directives option of hpcpy, albeit a bit clunky to achieve the same thing as payu.

I'd propose something like:

```python
client.submit(
    "job.sh",
    variables=dict(var1="myvar")
)
```

which would render something like this:

```shell
qsub -v var1=myvar job.sh
```

Obviously with the correct quoting etc as expected by `qsub`

**Comment by aidanheerdegen** [comment]
Seems reasonable. `payu` already creates a dictionary like this

https://github.com/payu-org/payu/blob/master/payu/cli.py#L98-L160

And then does some other stuff in `payu-run` (which looks like it is ripe for some cleaning up) to set a bunch of PBS variables

https://github.com/payu-org/payu/blob/master/payu/subcommands/run_cmd.py#L19-L110
